/* Regions include:
 * Africa
 * Americas
 * Asia
 * Europe
 * Middle East
 * Oceania
 * 
 */

const countries = [
    {'abbr': 'ac', 'name': "Ascension Island", 'region': ''},
    {'abbr': 'af', 'name': "Afghanistan", 'region': 'Middle East'},
    {'abbr': 'al', 'name': "Albania", 'region': 'Europe'},
    {'abbr': 'dz', 'name': "Algeria", 'region': ''},
    {'abbr': 'as', 'name': "American Samoa", 'region': ''},
    {'abbr': 'ad', 'name': "Andorra", 'region': ''},
    {'abbr': 'ao', 'name': "Angola", 'region': ''},
    {'abbr': 'ai', 'name': "Anguilla", 'region': ''},
    {'abbr': 'aq', 'name': "Antarctica", 'region': ''},
    {'abbr': 'ag', 'name': "Antigua and Barbuda", 'region': ''},
    {'abbr': 'ar', 'name': "Argentina", 'region': ''},
    {'abbr': 'am', 'name': "Armenia", 'region': ''},
    {'abbr': 'aw', 'name': "Aruba", 'region': ''},
    {'abbr': 'au', 'name': "Australia", 'region': ''},
    {'abbr': 'at', 'name': "Austria", 'region': ''},
    {'abbr': 'az', 'name': "Azerbaijan", 'region': ''},
    {'abbr': 'bs', 'name': "Bahamas", 'region': ''},
    {'abbr': 'bh', 'name': "Bahrain", 'region': ''},
    {'abbr': 'bd', 'name': "Bangladesh", 'region': ''},
    {'abbr': 'bb', 'name': "Barbados", 'region': ''},
    {'abbr': 'by', 'name': "Belarus", 'region': ''},
    {'abbr': 'be', 'name': "Belgium", 'region': ''},
    {'abbr': 'bz', 'name': "Belize", 'region': ''},
    {'abbr': 'bj', 'name': "Benin", 'region': ''},
    {'abbr': 'bm', 'name': "Bermuda", 'region': ''},
    {'abbr': 'bt', 'name': "Bhutan", 'region': ''},
    {'abbr': 'bo', 'name': "Bolivia", 'region': ''},
    {'abbr': 'bq', 'name': "Bonaire", 'region': ''},
    {'abbr': 'ba', 'name': "Bosnia and Herzegovina", 'region': ''},
    {'abbr': 'bw', 'name': "Botswana", 'region': ''},
    {'abbr': 'bv', 'name': "Bouvet Island", 'region': ''},
    {'abbr': 'br', 'name': "Brazil", 'region': ''},
    {'abbr': 'io', 'name': "British Indian Ocean Territory", 'region': ''},
    {'abbr': 'bn', 'name': "Brunei Darussalam", 'region': ''},
    {'abbr': 'bg', 'name': "Bulgaria", 'region': ''},
    {'abbr': 'bf', 'name': "Burkina Faso", 'region': ''},
    {'abbr': 'bi', 'name': "Burundi", 'region': ''},
    {'abbr': 'cv', 'name': "Cabo Verde", 'region': ''},
    {'abbr': 'kh', 'name': "Cambodia", 'region': ''},
    {'abbr': 'cm', 'name': "Cameroon", 'region': ''},
    {'abbr': 'ca', 'name': "Canada", 'region': ''},
    {'abbr': 'ky', 'name': "Cayman Islands", 'region': ''},
    {'abbr': 'cf', 'name': "Central African Republic", 'region': ''},
    {'abbr': 'td', 'name': "Chad", 'region': ''},
    {'abbr': 'cl', 'name': "Chile", 'region': ''},
    {'abbr': 'cn', 'name': "China", 'region': ''},
    {'abbr': 'cx', 'name': "Christmas Island", 'region': ''},
    {'abbr': 'cc', 'name': "Cocos (Keeling) Islands", 'region': ''},
    {'abbr': 'co', 'name': "Colombia", 'region': ''},
    {'abbr': 'km', 'name': "Comoros", 'region': ''},
    {'abbr': 'cd', 'name': "Congo (the Democratic Republic of the)", 'region': ''},
    {'abbr': 'cg', 'name': "Congo", 'region': ''},
    {'abbr': 'ck', 'name': "Cook Islands", 'region': ''},
    {'abbr': 'cr', 'name': "Costa Rica", 'region': ''},
    {'abbr': 'hr', 'name': "Croatia", 'region': ''},
    {'abbr': 'cu', 'name': "Cuba", 'region': ''},
    {'abbr': 'cw', 'name': "Curaçao", 'region': ''},
    {'abbr': 'cy', 'name': "Cyprus", 'region': ''},
    {'abbr': 'cz', 'name': "Czechia", 'region': ''},
    {'abbr': 'ci', 'name': "Côte d\'Ivoire", 'region': ''},
    {'abbr': 'dk', 'name': "Denmark", 'region': ''},
    {'abbr': 'dj', 'name': "Djibouti", 'region': ''},
    {'abbr': 'dm', 'name': "Dominica", 'region': ''},
    {'abbr': 'do', 'name': "Dominican Republic", 'region': ''},
    {'abbr': 'ec', 'name': "Ecuador", 'region': ''},
    {'abbr': 'eg', 'name': "Egypt", 'region': ''},
    {'abbr': 'sv', 'name': "El Salvador", 'region': ''},
    {'abbr': 'gq', 'name': "Equatorial Guinea", 'region': ''},
    {'abbr': 'er', 'name': "Eritrea", 'region': ''},
    {'abbr': 'ee', 'name': "Estonia", 'region': ''},
    {'abbr': 'sz', 'name': "Eswatini", 'region': ''},
    {'abbr': 'et', 'name': "Ethiopia", 'region': ''},
    {'abbr': 'fk', 'name': "Falkland Islands", 'region': ''},
    {'abbr': 'fo', 'name': "Faroe Islands", 'region': ''},
    {'abbr': 'fj', 'name': "Fiji", 'region': ''},
    {'abbr': 'fi', 'name': "Finland", 'region': ''},
    {'abbr': 'fr', 'name': "France", 'region': ''},
    {'abbr': 'gf', 'name': "French Guiana", 'region': ''},
    {'abbr': 'pf', 'name': "French Polynesia", 'region': ''},
    {'abbr': 'tf', 'name': "French Southern Territories", 'region': ''},
    {'abbr': 'ga', 'name': "Gabon", 'region': ''},
    {'abbr': 'gm', 'name': "Gambia (the)", 'region': ''},
    {'abbr': 'ge', 'name': "Georgia", 'region': ''},
    {'abbr': 'de', 'name': "Germany", 'region': ''},
    {'abbr': 'gh', 'name': "Ghana", 'region': ''},
    {'abbr': 'gi', 'name': "Gibraltar", 'region': ''},
    {'abbr': 'gr', 'name': "Greece", 'region': ''},
    {'abbr': 'gl', 'name': "Greenland", 'region': ''},
    {'abbr': 'gd', 'name': "Grenada", 'region': ''},
    {'abbr': 'gp', 'name': "Guadeloupe", 'region': ''},
    {'abbr': 'gu', 'name': "Guam", 'region': ''},
    {'abbr': 'gt', 'name': "Guatemala", 'region': ''},
    {'abbr': 'gg', 'name': "Guernsey", 'region': ''},
    {'abbr': 'gn', 'name': "Guinea", 'region': ''},
    {'abbr': 'gw', 'name': "Guinea-Bissau", 'region': ''},
    {'abbr': 'gy', 'name': "Guyana", 'region': ''},
    {'abbr': 'ht', 'name': "Haiti", 'region': ''},
    {'abbr': 'hm', 'name': "Heard Island and McDonald Islands", 'region': ''},
    {'abbr': 'va', 'name': "Holy See", 'region': ''},
    {'abbr': 'hn', 'name': "Honduras", 'region': ''},
    {'abbr': 'hk', 'name': "Hong Kong", 'region': ''},
    {'abbr': 'hu', 'name': "Hungary", 'region': ''},
    {'abbr': 'is', 'name': "Iceland", 'region': ''},
    {'abbr': 'in', 'name': "India", 'region': ''},
    {'abbr': 'id', 'name': "Indonesia", 'region': ''},
    {'abbr': 'ir', 'name': "Iran", 'region': ''},
    {'abbr': 'iq', 'name': "Iraq", 'region': ''},
    {'abbr': 'ie', 'name': "Ireland", 'region': ''},
    {'abbr': 'im', 'name': "Isle of Man", 'region': ''},
    {'abbr': 'il', 'name': "Israel", 'region': ''},
    {'abbr': 'it', 'name': "Italy", 'region': ''},
    {'abbr': 'jm', 'name': "Jamaica", 'region': ''},
    {'abbr': 'jp', 'name': "Japan", 'region': ''},
    {'abbr': 'je', 'name': "Jersey", 'region': ''},
    {'abbr': 'jo', 'name': "Jordan", 'region': ''},
    {'abbr': 'kz', 'name': "Kazakhstan", 'region': ''},
    {'abbr': 'ke', 'name': "Kenya", 'region': ''},
    {'abbr': 'ki', 'name': "Kiribati", 'region': ''},
    {'abbr': 'kp', 'name': "Korea (the Democratic People\'s Republic of)", 'region': ''},
    {'abbr': 'kr', 'name': "Korea (the Republic of)", 'region': ''},
    {'abbr': 'kw', 'name': "Kuwait", 'region': ''},
    {'abbr': 'kg', 'name': "Kyrgyzstan", 'region': ''},
    {'abbr': 'la', 'name': "Lao People\'s Democratic Republic", 'region': ''},
    {'abbr': 'lv', 'name': "Latvia", 'region': ''},
    {'abbr': 'lb', 'name': "Lebanon", 'region': ''},
    {'abbr': 'ls', 'name': "Lesotho", 'region': ''},
    {'abbr': 'lr', 'name': "Liberia", 'region': ''},
    {'abbr': 'ly', 'name': "Libya", 'region': ''},
    {'abbr': 'li', 'name': "Liechtenstein", 'region': ''},
    {'abbr': 'lt', 'name': "Lithuania", 'region': ''},
    {'abbr': 'lu', 'name': "Luxembourg", 'region': ''},
    {'abbr': 'mo', 'name': "Macao", 'region': ''},
    {'abbr': 'mg', 'name': "Madagascar", 'region': ''},
    {'abbr': 'mw', 'name': "Malawi", 'region': ''},
    {'abbr': 'my', 'name': "Malaysia", 'region': ''},
    {'abbr': 'mv', 'name': "Maldives", 'region': ''},
    {'abbr': 'ml', 'name': "Mali", 'region': ''},
    {'abbr': 'mt', 'name': "Malta", 'region': ''},
    {'abbr': 'mh', 'name': "Marshall Islands", 'region': ''},
    {'abbr': 'mq', 'name': "Martinique", 'region': ''},
    {'abbr': 'mr', 'name': "Mauritania", 'region': ''},
    {'abbr': 'mu', 'name': "Mauritius", 'region': ''},
    {'abbr': 'yt', 'name': "Mayotte", 'region': ''},
    {'abbr': 'mx', 'name': "Mexico", 'region': ''},
    {'abbr': 'fm', 'name': "Micronesia", 'region': ''},
    {'abbr': 'md', 'name': "Moldova", 'region': ''},
    {'abbr': 'mc', 'name': "Monaco", 'region': ''},
    {'abbr': 'mn', 'name': "Mongolia", 'region': ''},
    {'abbr': 'me', 'name': "Montenegro", 'region': ''},
    {'abbr': 'ms', 'name': "Montserrat", 'region': ''},
    {'abbr': 'ma', 'name': "Morocco", 'region': ''},
    {'abbr': 'mz', 'name': "Mozambique", 'region': ''},
    {'abbr': 'mm', 'name': "Myanmar", 'region': ''},
    {'abbr': 'na', 'name': "Namibia", 'region': ''},
    {'abbr': 'nr', 'name': "Nauru", 'region': ''},
    {'abbr': 'np', 'name': "Nepal", 'region': ''},
    {'abbr': 'nl', 'name': "Netherlands", 'region': ''},
    {'abbr': 'nc', 'name': "New Caledonia", 'region': ''},
    {'abbr': 'nz', 'name': "New Zealand", 'region': ''},
    {'abbr': 'ni', 'name': "Nicaragua", 'region': ''},
    {'abbr': 'ne', 'name': "Niger", 'region': ''},
    {'abbr': 'ng', 'name': "Nigeria", 'region': ''},
    {'abbr': 'nu', 'name': "Niue", 'region': ''},
    {'abbr': 'nf', 'name': "Norfolk Island", 'region': ''},
    {'abbr': 'mp', 'name': "Northern Mariana Islands", 'region': ''},
    {'abbr': 'no', 'name': "Norway", 'region': ''},
    {'abbr': 'om', 'name': "Oman", 'region': ''},
    {'abbr': 'pk', 'name': "Pakistan", 'region': ''},
    {'abbr': 'pw', 'name': "Palau", 'region': ''},
    {'abbr': 'ps', 'name': "Palestine State of", 'region': ''},
    {'abbr': 'pa', 'name': "Panama", 'region': ''},
    {'abbr': 'pg', 'name': "Papua New Guinea", 'region': ''},
    {'abbr': 'py', 'name': "Paraguay", 'region': ''},
    {'abbr': 'pe', 'name': "Peru", 'region': ''},
    {'abbr': 'ph', 'name': "Philippines (the)", 'region': ''},
    {'abbr': 'pn', 'name': "Pitcairn", 'region': ''},
    {'abbr': 'pl', 'name': "Poland", 'region': ''},
    {'abbr': 'pt', 'name': "Portugal", 'region': ''},
    {'abbr': 'pr', 'name': "Puerto Rico", 'region': ''},
    {'abbr': 'qa', 'name': "Qatar", 'region': ''},
    {'abbr': 'mk', 'name': "Republic of North Macedonia", 'region': ''},
    {'abbr': 'ro', 'name': "Romania", 'region': ''},
    {'abbr': 'ru', 'name': "Russian Federation", 'region': ''},
    {'abbr': 'rw', 'name': "Rwanda", 'region': ''},
    {'abbr': 're', 'name': "Réunion", 'region': ''},
    {'abbr': 'bl', 'name': "Saint Barthélemy", 'region': ''},
    {'abbr': 'sh', 'name': "Saint Helena", 'region': ''},
    {'abbr': 'kn', 'name': "Saint Kitts and Nevis", 'region': ''},
    {'abbr': 'lc', 'name': "Saint Lucia", 'region': ''},
    {'abbr': 'mf', 'name': "Saint Martin (French part)", 'region': ''},
    {'abbr': 'pm', 'name': "Saint Pierre and Miquelon", 'region': ''},
    {'abbr': 'vc', 'name': "Saint Vincent and the Grenadines", 'region': ''},
    {'abbr': 'ws', 'name': "Samoa", 'region': ''},
    {'abbr': 'sm', 'name': "San Marino", 'region': ''},
    {'abbr': 'st', 'name': "Sao Tome and Principe", 'region': ''},
    {'abbr': 'sa', 'name': "Saudi Arabia", 'region': ''},
    {'abbr': 'sn', 'name': "Senegal", 'region': ''},
    {'abbr': 'rs', 'name': "Serbia", 'region': ''},
    {'abbr': 'sc', 'name': "Seychelles", 'region': ''},
    {'abbr': 'sl', 'name': "Sierra Leone", 'region': ''},
    {'abbr': 'sg', 'name': "Singapore", 'region': ''},
    {'abbr': 'sx', 'name': "Sint Maarten (Dutch part)", 'region': ''},
    {'abbr': 'sk', 'name': "Slovakia", 'region': ''},
    {'abbr': 'si', 'name': "Slovenia", 'region': ''},
    {'abbr': 'sb', 'name': "Solomon Islands", 'region': ''},
    {'abbr': 'so', 'name': "Somalia", 'region': ''},
    {'abbr': 'za', 'name': "South Africa", 'region': ''},
    {'abbr': 'gs', 'name': "South Georgia and the South Sandwich Islands", 'region': ''},
    {'abbr': 'ss', 'name': "South Sudan", 'region': ''},
    {'abbr': 'es', 'name': "Spain", 'region': ''},
    {'abbr': 'lk', 'name': "Sri Lanka", 'region': ''},
    {'abbr': 'sd', 'name': "Sudan (the)", 'region': ''},
    {'abbr': 'sr', 'name': "Suriname", 'region': ''},
    {'abbr': 'sj', 'name': "Svalbard and Jan Mayen", 'region': ''},
    {'abbr': 'se', 'name': "Sweden", 'region': ''},
    {'abbr': 'ch', 'name': "Switzerland", 'region': ''},
    {'abbr': 'sy', 'name': "Syrian Arab Republic", 'region': ''},
    {'abbr': 'tw', 'name': "Taiwan", 'region': ''},
    {'abbr': 'tj', 'name': "Tajikistan", 'region': ''},
    {'abbr': 'tz', 'name': "Tanzania", 'region': ''},
    {'abbr': 'th', 'name': "Thailand", 'region': ''},
    {'abbr': 'tl', 'name': "Timor-Leste", 'region': ''},
    {'abbr': 'tg', 'name': "Togo", 'region': ''},
    {'abbr': 'tk', 'name': "Tokelau", 'region': ''},
    {'abbr': 'to', 'name': "Tonga", 'region': ''},
    {'abbr': 'tt', 'name': "Trinidad and Tobago", 'region': ''},
    {'abbr': 'tn', 'name': "Tunisia", 'region': ''},
    {'abbr': 'tr', 'name': "Turkey", 'region': ''},
    {'abbr': 'tm', 'name': "Turkmenistan", 'region': ''},
    {'abbr': 'tc', 'name': "Turks and Caicos Islands", 'region': ''},
    {'abbr': 'tv', 'name': "Tuvalu", 'region': ''},
    {'abbr': 'ug', 'name': "Uganda", 'region': ''},
    {'abbr': 'ua', 'name': "Ukraine", 'region': ''},
    {'abbr': 'ae', 'name': "United Arab Emirates", 'region': ''},
    {'abbr': 'gb', 'name': "United Kingdom of Great Britain and Northern Ireland", 'region': ''},
    {'abbr': 'um', 'name': "United States Minor Outlying Islands", 'region': ''},
    {'abbr': 'us', 'name': "United States of America", 'region': ''},
    {'abbr': 'uy', 'name': "Uruguay", 'region': ''},
    {'abbr': 'uz', 'name': "Uzbekistan", 'region': ''},
    {'abbr': 'vu', 'name': "Vanuatu", 'region': ''},
    {'abbr': 've', 'name': "Venezuela (Bolivarian Republic of)", 'region': ''},
    {'abbr': 'vn', 'name': "Viet Nam", 'region': ''},
    {'abbr': 'vg', 'name': "Virgin Islands (British)", 'region': ''},
    {'abbr': 'vi', 'name': "Virgin Islands (U.S.)", 'region': ''},
    {'abbr': 'wf', 'name': "Wallis and Futuna", 'region': ''},
    {'abbr': 'eh', 'name': "Western Sahara", 'region': ''},
    {'abbr': 'ye', 'name': "Yemen", 'region': ''},
    {'abbr': 'zm', 'name': "Zambia", 'region': ''},
    {'abbr': 'zw', 'name': "Zimbabwe", 'region': ''},
    {'abbr': 'ax', 'name': "Åland Islands", 'region': ''}
]

/* Helper Functions */

function populateCountries() {
    /* Populates countries in the Options selection. */
    var selectionBox = document.getElementById("countries");
    countries.forEach(e => {
        var opt = document.createElement("option");
        var text = document.createTextNode(e["name"]);
        opt.value = e["abbr"]
        opt.appendChild(text);
        selectionBox.appendChild(opt);
    });
}

function getRandomFlag(array = countries) {
    /* Gets a random flag, given parameters. */
    return array[Math.floor(Math.random() * array.length)];
}

function submitGuess() {
    /* Gets the user's guess in the selection and compares it to the 
       chosen random flag. */
    let e = document.getElementById("countries");
    let selectedCountryAbbr = e.options[e.selectedIndex].value;

    if (window.flagData['abbr'] == selectedCountryAbbr) {
        alert(`Yep! It was ${window.flagData['name']}.`);
    } else {
        alert(`Nope! It was ${window.flagData['name']}.`)
    }
}

function resetFlag() {
    /* Resets the flag and restarts the round. */
    window.flagData = getRandomFlag();
    $("#flag").attr("src", `assets/images/${window.flagData['abbr']}.svg`);
}