function getRandomFlagFile(array = flagFiles) {
    return array[Math.floor(Math.random() * array.length)];
}

var flagFiles = ['ad.svg', 'ae.svg', 'af.svg', 'ag.svg', 'ai.svg', 'al.svg', 'am.svg', 'ao.svg', 'aq.svg', 'ar.svg', 'as.svg', 'at.svg', 'au.svg', 'aw.svg', 'ax.svg', 'az.svg', 'ba.svg', 'bb.svg', 'bd.svg', 'be.svg', 'bf.svg', 'bg.svg', 'bh.svg', 'bi.svg', 'bj.svg', 'bl.svg', 'bm.svg', 'bn.svg', 'bo.svg', 'bq.svg', 'br.svg', 'bs.svg', 'bt.svg', 'bv.svg', 'bw.svg', 'by.svg', 'bz.svg', 'ca.svg', 'cc.svg', 'cd.svg', 'cf.svg', 'cg.svg', 'ch.svg', 'ci.svg', 'ck.svg', 'cl.svg', 'cm.svg', 'cn.svg', 'co.svg', 'cr.svg', 'cu.svg', 'cv.svg', 'cw.svg', 'cx.svg', 'cy.svg', 'cz.svg', 'de.svg', 'dj.svg', 'dk.svg', 'dm.svg', 'do.svg', 'dz.svg', 'ec.svg', 'ee.svg', 'eg.svg', 'eh.svg', 'er.svg', 'es.svg', 'et.svg', 'fi.svg', 'fj.svg', 'fk.svg', 'fm.svg', 'fo.svg', 'fr.svg', 'ga.svg', 'gb-eng.svg', 'gb-nir.svg', 'gb-sct.svg', 'gb-wls.svg', 'gb.svg', 'gd.svg', 'ge.svg', 'gf.svg', 'gg.svg', 'gh.svg', 'gi.svg', 'gl.svg', 'gm.svg', 'gn.svg', 'gp.svg', 'gq.svg', 'gr.svg', 'gs.svg', 'gt.svg', 'gu.svg', 'gw.svg', 'gy.svg', 'hk.svg', 'hm.svg', 'hn.svg', 'hr.svg', 'ht.svg', 'hu.svg', 'id.svg', 'ie.svg', 'il.svg', 'im.svg', 'in.svg', 'io.svg', 'iq.svg', 'ir.svg', 'is.svg', 'it.svg', 'je.svg', 'jm.svg', 'jo.svg', 'jp.svg', 'ke.svg', 'kg.svg', 'kh.svg', 'ki.svg', 'km.svg', 'kn.svg', 'kp.svg', 'kr.svg', 'kw.svg', 'ky.svg', 'kz.svg', 'la.svg', 'lb.svg', 'lc.svg', 'li.svg', 'lk.svg', 'lr.svg', 'ls.svg', 'lt.svg', 'lu.svg', 'lv.svg', 'ly.svg', 'ma.svg', 'mc.svg', 'md.svg', 'me.svg', 'mf.svg', 'mg.svg', 'mh.svg', 'mk.svg', 'ml.svg', 'mm.svg', 'mn.svg', 'mo.svg', 'mp.svg', 'mq.svg', 'mr.svg', 'ms.svg', 'mt.svg', 'mu.svg', 'mv.svg', 'mw.svg', 'mx.svg', 'my.svg', 'mz.svg', 'na.svg', 'nc.svg', 'ne.svg', 'nf.svg', 'ng.svg', 'ni.svg', 'nl.svg', 'no.svg', 'np.svg', 'nr.svg', 'nu.svg', 'nz.svg', 'om.svg', 'pa.svg', 'pe.svg', 'pf.svg', 'pg.svg', 'ph.svg', 'pk.svg', 'pl.svg', 'pm.svg', 'pn.svg', 'pr.svg', 'ps.svg', 'pt.svg', 'pw.svg', 'py.svg', 'qa.svg', 're.svg', 'ro.svg', 'rs.svg', 'ru.svg', 'rw.svg', 'sa.svg', 'sb.svg', 'sc.svg', 'sd.svg', 'se.svg', 'sg.svg', 'sh.svg', 'si.svg', 'sj.svg', 'sk.svg', 'sl.svg', 'sm.svg', 'sn.svg', 'so.svg', 'sr.svg', 'ss.svg', 'st.svg', 'sv.svg', 'sx.svg', 'sy.svg', 'sz.svg', 'tc.svg', 'td.svg', 'tf.svg', 'tg.svg', 'th.svg', 'tj.svg', 'tk.svg', 'tl.svg', 'tm.svg', 'tn.svg', 'to.svg', 'tr.svg', 'tt.svg', 'tv.svg', 'tw.svg', 'tz.svg', 'ua.svg', 'ug.svg', 'um.svg', 'us.svg', 'uy.svg', 'uz.svg', 'va.svg', 'vc.svg', 've.svg', 'vg.svg', 'vi.svg', 'vn.svg', 'vu.svg', 'wf.svg', 'ws.svg', 'xk.svg', 'ye.svg', 'yt.svg', 'za.svg', 'zm.svg', 'zw.svg'];

var flagAbbr = flagFiles.map(function (i) {
    return i.replace(".svg", "")
});

var flagAbbrToNameMap = {
    'af': 'Afghanistan',
    'al': 'Albania',
    'dz': 'Algeria',
    'as': 'American Samoa',
    'ad': 'Andorra',
    'ao': 'Angola',
    'ai': 'Anguilla',
    'aq': 'Antarctica',
    'ag': 'Antigua and Barbuda',
    'ar': 'Argentina',
    'am': 'Armenia',
    'aw': 'Aruba',
    'au': 'Australia',
    'at': 'Austria',
    'az': 'Azerbaijan',
    'bs': 'Bahamas',
    'bh': 'Bahrain',
    'bd': 'Bangladesh',
    'bb': 'Barbados',
    'by': 'Belarus',
    'be': 'Belgium',
    'bz': 'Belize',
    'bj': 'Benin',
    'bm': 'Bermuda',
    'bt': 'Bhutan',
    'bo': 'Bolivia',
    'bq': 'Bonaire',
    'ba': 'Bosnia and Herzegovina',
    'bw': 'Botswana',
    'bv': 'Bouvet Island',
    'br': 'Brazil',
    'io': 'British Indian Ocean Territory',
    'bn': 'Brunei Darussalam',
    'bg': 'Bulgaria',
    'bf': 'Burkina Faso',
    'bi': 'Burundi',
    'cv': 'Cabo Verde',
    'kh': 'Cambodia',
    'cm': 'Cameroon',
    'ca': 'Canada',
    'ky': 'Cayman Islands',
    'cf': 'Central African Republic',
    'td': 'Chad',
    'cl': 'Chile',
    'cn': 'China',
    'cx': 'Christmas Island',
    'cc': 'Cocos (Keeling) Islands',
    'co': 'Colombia',
    'km': 'Comoros',
    'cd': 'Congo (the Democratic Republic of the)',
    'cg': 'Congo',
    'ck': 'Cook Islands',
    'cr': 'Costa Rica',
    'hr': 'Croatia',
    'cu': 'Cuba',
    'cw': 'Curaçao',
    'cy': 'Cyprus',
    'cz': 'Czechia',
    'ci': 'Côte d\'Ivoire',
    'dk': 'Denmark',
    'dj': 'Djibouti',
    'dm': 'Dominica',
    'do': 'Dominican Republic',
    'ec': 'Ecuador',
    'eg': 'Egypt',
    'sv': 'El Salvador',
    'gq': 'Equatorial Guinea',
    'er': 'Eritrea',
    'ee': 'Estonia',
    'sz': 'Eswatini',
    'et': 'Ethiopia',
    'fk': 'Falkland Islands',
    'fo': 'Faroe Islands',
    'fj': 'Fiji',
    'fi': 'Finland',
    'fr': 'France',
    'gf': 'French Guiana',
    'pf': 'French Polynesia',
    'tf': 'French Southern Territories',
    'ga': 'Gabon',
    'gm': 'Gambia (the)',
    'ge': 'Georgia',
    'de': 'Germany',
    'gh': 'Ghana',
    'gi': 'Gibraltar',
    'gr': 'Greece',
    'gl': 'Greenland',
    'gd': 'Grenada',
    'gp': 'Guadeloupe',
    'gu': 'Guam',
    'gt': 'Guatemala',
    'gg': 'Guernsey',
    'gn': 'Guinea',
    'gw': 'Guinea-Bissau',
    'gy': 'Guyana',
    'ht': 'Haiti',
    'hm': 'Heard Island and McDonald Islands',
    'va': 'Holy See',
    'hn': 'Honduras',
    'hk': 'Hong Kong',
    'hu': 'Hungary',
    'is': 'Iceland',
    'in': 'India',
    'id': 'Indonesia',
    'ir': 'Iran',
    'iq': 'Iraq',
    'ie': 'Ireland',
    'im': 'Isle of Man',
    'il': 'Israel',
    'it': 'Italy',
    'jm': 'Jamaica',
    'jp': 'Japan',
    'je': 'Jersey',
    'jo': 'Jordan',
    'kz': 'Kazakhstan',
    'ke': 'Kenya',
    'ki': 'Kiribati',
    'kp': 'Korea (the Democratic People\'s Republic of)',
    'kr': 'Korea (the Republic of)',
    'kw': 'Kuwait',
    'kg': 'Kyrgyzstan',
    'la': 'Lao People\'s Democratic Republic',
    'lv': 'Latvia',
    'lb': 'Lebanon',
    'ls': 'Lesotho',
    'lr': 'Liberia',
    'ly': 'Libya',
    'li': 'Liechtenstein',
    'lt': 'Lithuania',
    'lu': 'Luxembourg',
    'mo': 'Macao',
    'mg': 'Madagascar',
    'mw': 'Malawi',
    'my': 'Malaysia',
    'mv': 'Maldives',
    'ml': 'Mali',
    'mt': 'Malta',
    'mh': 'Marshall Islands',
    'mq': 'Martinique',
    'mr': 'Mauritania',
    'mu': 'Mauritius',
    'yt': 'Mayotte',
    'mx': 'Mexico',
    'fm': 'Micronesia',
    'md': 'Moldova',
    'mc': 'Monaco',
    'mn': 'Mongolia',
    'me': 'Montenegro',
    'ms': 'Montserrat',
    'ma': 'Morocco',
    'mz': 'Mozambique',
    'mm': 'Myanmar',
    'na': 'Namibia',
    'nr': 'Nauru',
    'np': 'Nepal',
    'nl': 'Netherlands',
    'nc': 'New Caledonia',
    'nz': 'New Zealand',
    'ni': 'Nicaragua',
    'ne': 'Niger',
    'ng': 'Nigeria',
    'nu': 'Niue',
    'nf': 'Norfolk Island',
    'mp': 'Northern Mariana Islands',
    'no': 'Norway',
    'om': 'Oman',
    'pk': 'Pakistan',
    'pw': 'Palau',
    'ps': 'Palestine, State of',
    'pa': 'Panama',
    'pg': 'Papua New Guinea',
    'py': 'Paraguay',
    'pe': 'Peru',
    'ph': 'Philippines (the)',
    'pn': 'Pitcairn',
    'pl': 'Poland',
    'pt': 'Portugal',
    'pr': 'Puerto Rico',
    'qa': 'Qatar',
    'mk': 'Republic of North Macedonia',
    'ro': 'Romania',
    'ru': 'Russian Federation',
    'rw': 'Rwanda',
    're': 'Réunion',
    'bl': 'Saint Barthélemy',
    'sh': 'Saint Helena',
    'kn': 'Saint Kitts and Nevis',
    'lc': 'Saint Lucia',
    'mf': 'Saint Martin (French part)',
    'pm': 'Saint Pierre and Miquelon',
    'vc': 'Saint Vincent and the Grenadines',
    'ws': 'Samoa',
    'sm': 'San Marino',
    'st': 'Sao Tome and Principe',
    'sa': 'Saudi Arabia',
    'sn': 'Senegal',
    'rs': 'Serbia',
    'sc': 'Seychelles',
    'sl': 'Sierra Leone',
    'sg': 'Singapore',
    'sx': 'Sint Maarten (Dutch part)',
    'sk': 'Slovakia',
    'si': 'Slovenia',
    'sb': 'Solomon Islands',
    'so': 'Somalia',
    'za': 'South Africa',
    'gs': 'South Georgia and the South Sandwich Islands',
    'ss': 'South Sudan',
    'es': 'Spain',
    'lk': 'Sri Lanka',
    'sd': 'Sudan (the)',
    'sr': 'Suriname',
    'sj': 'Svalbard and Jan Mayen',
    'se': 'Sweden',
    'ch': 'Switzerland',
    'sy': 'Syrian Arab Republic',
    'tw': 'Taiwan',
    'tj': 'Tajikistan',
    'tz': 'Tanzania',
    'th': 'Thailand',
    'tl': 'Timor-Leste',
    'tg': 'Togo',
    'tk': 'Tokelau',
    'to': 'Tonga',
    'tt': 'Trinidad and Tobago',
    'tn': 'Tunisia',
    'tr': 'Turkey',
    'tm': 'Turkmenistan',
    'tc': 'Turks and Caicos Islands',
    'tv': 'Tuvalu',
    'ug': 'Uganda',
    'ua': 'Ukraine',
    'ae': 'United Arab Emirates',
    'gb': 'United Kingdom of Great Britain and Northern Ireland',
    'um': 'United States Minor Outlying Islands',
    'us': 'United States of America',
    'uy': 'Uruguay',
    'uz': 'Uzbekistan',
    'vu': 'Vanuatu',
    've': 'Venezuela (Bolivarian Republic of)',
    'vn': 'Viet Nam',
    'vg': 'Virgin Islands (British)',
    'vi': 'Virgin Islands (U.S.)',
    'wf': 'Wallis and Futuna',
    'eh': 'Western Sahara',
    'ye': 'Yemen',
    'zm': 'Zambia',
    'zw': 'Zimbabwe',
    'ax': 'Åland Islands'
}

var flagNameToAbbrMap = {
    'Afghanistan': 'af',
    'Albania': 'al',
    'Algeria': 'dz',
    'American Samoa': 'as',
    'Andorra': 'ad',
    'Angola': 'ao',
    'Anguilla': 'ai',
    'Antarctica': 'aq',
    'Antigua and Barbuda': 'ag',
    'Argentina': 'ar',
    'Armenia': 'am',
    'Aruba': 'aw',
    'Australia': 'au',
    'Austria': 'at',
    'Azerbaijan': 'az',
    'Bahamas': 'bs',
    'Bahrain': 'bh',
    'Bangladesh': 'bd',
    'Barbados': 'bb',
    'Belarus': 'by',
    'Belgium': 'be',
    'Belize': 'bz',
    'Benin': 'bj',
    'Bermuda': 'bm',
    'Bhutan': 'bt',
    'Bolivia': 'bo',
    'Bonaire': 'bq',
    'Bosnia and Herzegovina': 'ba',
    'Botswana': 'bw',
    'Bouvet Island': 'bv',
    'Brazil': 'br',
    'British Indian Ocean Territory': 'io',
    'Brunei Darussalam': 'bn',
    'Bulgaria': 'bg',
    'Burkina Faso': 'bf',
    'Burundi': 'bi',
    'Cabo Verde': 'cv',
    'Cambodia': 'kh',
    'Cameroon': 'cm',
    'Canada': 'ca',
    'Cayman Islands': 'ky',
    'Central African Republic': 'cf',
    'Chad': 'td',
    'Chile': 'cl',
    'China': 'cn',
    'Christmas Island': 'cx',
    'Cocos (Keeling) Islands': 'cc',
    'Colombia': 'co',
    'Comoros': 'km',
    'Congo (the Democratic Republic of the)': 'cd',
    'Congo': 'cg',
    'Cook Islands': 'ck',
    'Costa Rica': 'cr',
    'Croatia': 'hr',
    'Cuba': 'cu',
    'Curaçao': 'cw',
    'Cyprus': 'cy',
    'Czechia': 'cz',
    'Côte d\'Ivoire': 'ci',
    'Denmark': 'dk',
    'Djibouti': 'dj',
    'Dominica': 'dm',
    'Dominican Republic': 'do',
    'Ecuador': 'ec',
    'Egypt': 'eg',
    'El Salvador': 'sv',
    'Equatorial Guinea': 'gq',
    'Eritrea': 'er',
    'Estonia': 'ee',
    'Eswatini': 'sz',
    'Ethiopia': 'et',
    'Falkland Islands': 'fk',
    'Faroe Islands': 'fo',
    'Fiji': 'fj',
    'Finland': 'fi',
    'France': 'fr',
    'French Guiana': 'gf',
    'French Polynesia': 'pf',
    'French Southern Territories': 'tf',
    'Gabon': 'ga',
    'Gambia (the)': 'gm',
    'Georgia': 'ge',
    'Germany': 'de',
    'Ghana': 'gh',
    'Gibraltar': 'gi',
    'Greece': 'gr',
    'Greenland': 'gl',
    'Grenada': 'gd',
    'Guadeloupe': 'gp',
    'Guam': 'gu',
    'Guatemala': 'gt',
    'Guernsey': 'gg',
    'Guinea': 'gn',
    'Guinea-Bissau': 'gw',
    'Guyana': 'gy',
    'Haiti': 'ht',
    'Heard Island and McDonald Islands': 'hm',
    'Holy See': 'va',
    'Honduras': 'hn',
    'Hong Kong': 'hk',
    'Hungary': 'hu',
    'Iceland': 'is',
    'India': 'in',
    'Indonesia': 'id',
    'Iran': 'ir',
    'Iraq': 'iq',
    'Ireland': 'ie',
    'Isle of Man': 'im',
    'Israel': 'il',
    'Italy': 'it',
    'Jamaica': 'jm',
    'Japan': 'jp',
    'Jersey': 'je',
    'Jordan': 'jo',
    'Kazakhstan': 'kz',
    'Kenya': 'ke',
    'Kiribati': 'ki',
    'Korea (the Democratic People\'s Republic of)': 'kp',
    'Korea (the Republic of)': 'kr',
    'Kuwait': 'kw',
    'Kyrgyzstan': 'kg',
    'Lao People\'s Democratic Republic': 'la',
    'Latvia': 'lv',
    'Lebanon': 'lb',
    'Lesotho': 'ls',
    'Liberia': 'lr',
    'Libya': 'ly',
    'Liechtenstein': 'li',
    'Lithuania': 'lt',
    'Luxembourg': 'lu',
    'Macao': 'mo',
    'Madagascar': 'mg',
    'Malawi': 'mw',
    'Malaysia': 'my',
    'Maldives': 'mv',
    'Mali': 'ml',
    'Malta': 'mt',
    'Marshall Islands': 'mh',
    'Martinique': 'mq',
    'Mauritania': 'mr',
    'Mauritius': 'mu',
    'Mayotte': 'yt',
    'Mexico': 'mx',
    'Micronesia': 'fm',
    'Moldova': 'md',
    'Monaco': 'mc',
    'Mongolia': 'mn',
    'Montenegro': 'me',
    'Montserrat': 'ms',
    'Morocco': 'ma',
    'Mozambique': 'mz',
    'Myanmar': 'mm',
    'Namibia': 'na',
    'Nauru': 'nr',
    'Nepal': 'np',
    'Netherlands': 'nl',
    'New Caledonia': 'nc',
    'New Zealand': 'nz',
    'Nicaragua': 'ni',
    'Niger': 'ne',
    'Nigeria': 'ng',
    'Niue': 'nu',
    'Norfolk Island': 'nf',
    'Northern Mariana Islands': 'mp',
    'Norway': 'no',
    'Oman': 'om',
    'Pakistan': 'pk',
    'Palau': 'pw',
    'Palestine, State of': 'ps',
    'Panama': 'pa',
    'Papua New Guinea': 'pg',
    'Paraguay': 'py',
    'Peru': 'pe',
    'Philippines (the)': 'ph',
    'Pitcairn': 'pn',
    'Poland': 'pl',
    'Portugal': 'pt',
    'Puerto Rico': 'pr',
    'Qatar': 'qa',
    'Republic of North Macedonia': 'mk',
    'Romania': 'ro',
    'Russian Federation': 'ru',
    'Rwanda': 'rw',
    'Réunion': 're',
    'Saint Barthélemy': 'bl',
    'Saint Helena': 'sh',
    'Saint Kitts and Nevis': 'kn',
    'Saint Lucia': 'lc',
    'Saint Martin (French part)': 'mf',
    'Saint Pierre and Miquelon': 'pm',
    'Saint Vincent and the Grenadines': 'vc',
    'Samoa': 'ws',
    'San Marino': 'sm',
    'Sao Tome and Principe': 'st',
    'Saudi Arabia': 'sa',
    'Senegal': 'sn',
    'Serbia': 'rs',
    'Seychelles': 'sc',
    'Sierra Leone': 'sl',
    'Singapore': 'sg',
    'Sint Maarten (Dutch part)': 'sx',
    'Slovakia': 'sk',
    'Slovenia': 'si',
    'Solomon Islands': 'sb',
    'Somalia': 'so',
    'South Africa': 'za',
    'South Georgia and the South Sandwich Islands': 'gs',
    'South Sudan': 'ss',
    'Spain': 'es',
    'Sri Lanka': 'lk',
    'Sudan (the)': 'sd',
    'Suriname': 'sr',
    'Svalbard and Jan Mayen': 'sj',
    'Sweden': 'se',
    'Switzerland': 'ch',
    'Syrian Arab Republic': 'sy',
    'Taiwan': 'tw',
    'Tajikistan': 'tj',
    'Tanzania': 'tz',
    'Thailand': 'th',
    'Timor-Leste': 'tl',
    'Togo': 'tg',
    'Tokelau': 'tk',
    'Tonga': 'to',
    'Trinidad and Tobago': 'tt',
    'Tunisia': 'tn',
    'Turkey': 'tr',
    'Turkmenistan': 'tm',
    'Turks and Caicos Islands': 'tc',
    'Tuvalu': 'tv',
    'Uganda': 'ug',
    'Ukraine': 'ua',
    'United Arab Emirates': 'ae',
    'United Kingdom of Great Britain and Northern Ireland': 'gb',
    'United States Minor Outlying Islands': 'um',
    'United States of America': 'us',
    'Uruguay': 'uy',
    'Uzbekistan': 'uz',
    'Vanuatu': 'vu',
    'Venezuela (Bolivarian Republic of)': 've',
    'Viet Nam': 'vn',
    'Virgin Islands (British)': 'vg',
    'Virgin Islands (U.S.)': 'vi',
    'Wallis and Futuna': 'wf',
    'Western Sahara': 'eh',
    'Yemen': 'ye',
    'Zambia': 'zm',
    'Zimbabwe': 'zw',
    'Åland Islands': 'ax'
}